[module]
  [module.hugoVersion]
    min = "0.95.0"

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.PRINT]
    name= "PRINT"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  [outputFormats.SEARCH]
    name= "SEARCH"
    baseName = "index.search"
    isPlainText = true
    mediaType = 'text/javascript'
    permalinkable = false
    noUgly = true

  [outputFormats.SERCHPAGE]
    name= "SEARCHPAGE"
    baseName = "search"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  # [x] russfeld
  [outputFormats.TELE]
    name= "TELE"
    baseName = "tele"
    # path = "tele.html"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false

  [outputFormats.EMBED]
    name= "EMBED"
    baseName = "embed"
    # path = "embed.html"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = true
